Repository googleapis/nodejs-precise-date, pull requests merged in 2020-07, with the labels that each got.

#120 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#121 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#123 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#126 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#127 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#128 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#129 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#130 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#132 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
